In [6]:
arr2=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("3D array:")
print(arr2)
new_arr=arr2.reshape(4,2)
print("reshaped array:")
print(new_arr)

3D array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
reshaped array:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [2]:
arr1=np.array([[1,2,3],[4,5,6]])
print("2D array:")
print(arr1)

2D array:
[[1 2 3]
 [4 5 6]]


In [1]:
import numpy as np
arr=np.array([10,20,30,40,50])
print("1D array:")
print(arr)

1D array:
[10 20 30 40 50]
