In [3]:

import numpy as np
print("NumPy version:",np.__version__)

NumPy version: 2.5.1


In [8]:
#1D array
arr1=np.array([1,2,3,4,5,6])
print("1D array:",arr1)

#2D array
arr2=np.array([[1,2,3],[4,5,6]])
print("2D array:",arr2)

#3D array
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("3D array:",arr3)

1D array: [1 2 3 4 5 6]
2D array: [[1 2 3]
 [4 5 6]]
3D array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
#zeros array
zeros_arr=np.zeros((2,3))
print("array of zeros:",zeros_arr)

#ones array
ones_arr=np.ones((2,3))
print("array of ones:",ones_arr)

#array filled with a constant value
full_arr=np.full((2,2),7)
print("full array:",full_arr)

#identity matrix
identity_arr=np.eye(4)
print("Identity matrix:",identity_arr)

array of zeros: [[0. 0. 0.]
 [0. 0. 0.]]
array of ones: [[1. 1. 1.]
 [1. 1. 1.]]
full array: [[7 7]
 [7 7]]
Identity matrix: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
# arange -> similar to Python range() but returns an array
range_arr=np.arange(0,10,2)
print("arange array:",range_arr)

# linspace -> evenly spaced numbers between start and stop (inclusive)
lin_arr=np.linspace(0,1,5)
print("linspace array:",lin_arr)

# Random arrays
rand_arr=np.random.rand(2,3)
radient_arr=np.random.randint(1, 100, size=(2, 3))
print("random float array:",rand_arr)
print("random integer array:",radient_arr)

arange array: [0 2 4 6 8]
linspace array: [0.   0.25 0.5  0.75 1.  ]
random float array: [[0.21204636 0.32101198 0.02231494]
 [0.127867   0.00388136 0.11481274]]
random integer array: [[ 6 75 57]
 [31 25 70]]


In [18]:
sample=np.array([[1,2,3],[4,5,6]])
print("Array:",sample)
print("shape:",sample.shape)
print("dimension:",sample.ndim)
print("size:",sample.size)
print("data type:",sample.dtype)

Array: [[1 2 3]
 [4 5 6]]
shape: (2, 3)
dimension: 2
size: 6
data type: int64


In [ ]:
#reshaping array
reshaped=sample.reshape(3,2)
print("Reshaped array:",reshaped)

# Flattening to 1D
flat = sample.flatten()
print("Flattened:", flat)

#transposing (swap rows and columns)
print("transpose:",sample.T)

Reshaped array: [[1 2]
 [3 4]
 [5 6]]
Flattened: [1 2 3 4 5 6]
transpose: [[1 4]
 [2 5]
 [3 6]]


In [26]:
#joining array
a=np.array([1,2,3])
b=np.array([4,5,6])

joined=np.concatenate((a,b))
print("concatenated:",joined)

stacked_v = np.vstack((a, b))   # vertical stack
stacked_h = np.hstack((a,b))    # horizontal stack

print("Vertical stack:\n", stacked_v)
print("Horizontal stack:", stacked_h)

concatenated: [1 2 3 4 5 6]
Vertical stack:
 [[1 2 3]
 [4 5 6]]
Horizontal stack: [1 2 3 4 5 6]


In [27]:
# Sorting arrays
unsorted = np.array([5, 2, 9, 1, 7])
sorted_arr = np.sort(unsorted)
print("Original:", unsorted)
print("Sorted:", sorted_arr)

Original: [5 2 9 1 7]
Sorted: [1 2 5 7 9]


In [28]:
ex2 = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", ex2.shape)
print("Size:", ex2.size)
print("Reshaped:\n", ex2.reshape(3, 2))

Shape: (2, 3)
Size: 6
Reshaped:
 [[1 2]
 [3 4]
 [5 6]]


In [29]:
x = np.array([10, 20, 30, 40])
y = np.array([1, 2, 3, 4])

print("Addition:", x + y)
print("Subtraction:", x - y)
print("Multiplication:", x * y)
print("Division:", x / y)
print("Power:", x ** 2)

Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Power: [ 100  400  900 1600]


In [34]:
data = np.array([4, 8, 15, 16, 23, 42])

print("sum",np.sum(data))
print("Mean",np.mean(data))
print("minimum",np.min(data))
print("maximum",np.max(data))
print("standard deviation",np.std(data))
print("variance",np.var(data))

sum 108
Mean 18.0
minimum 4
maximum 42
standard deviation 12.315302134607444
variance 151.66666666666666


In [37]:
# Universal functions work element-wise
nums=np.array([1,4,9,16])
print("Square root:", np.sqrt(nums))
print("exponential",np.exp(nums))
print("natural log:", np.log(nums))
print("Sine:", np.sin(nums))

Square root: [1. 2. 3. 4.]
exponential [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
natural log: [0.         1.38629436 2.19722458 2.77258872]
Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332]


In [38]:
# Matrix operations
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

print("Element-wise multiplication:\n", m1 * m2)
print("Matrix multiplication (dot):\n", np.dot(m1, m2))
print("Matrix multiplication (matmul):\n", np.matmul(m1, m2))

Element-wise multiplication:
 [[ 5 12]
 [21 32]]
Matrix multiplication (dot):
 [[19 22]
 [43 50]]
Matrix multiplication (matmul):
 [[19 22]
 [43 50]]


In [39]:
p = np.array([2, 4, 6, 8, 10])
q = np.array([1, 3, 5, 7, 9])

ex3_sum = p + q
ex3_product = p * q
print("Sum:", ex3_sum)
print("Product:", ex3_product)
print("Mean of sum:", np.mean(ex3_sum))

Sum: [ 3  7 11 15 19]
Product: [ 2 12 30 56 90]
Mean of sum: 11.0


In [42]:
arr = np.array([10, 20, 30, 40, 50, 60])
print("full array:",arr)
print("First element:", arr[0])
print("last element:", arr[-1])
print("Elements from index 1 to 3:", arr[1:4])
print("Every second element:", arr[::2])
print("Reversed array:", arr[::-1])

full array: [10 20 30 40 50 60]
First element: 10
last element: 60
Elements from index 1 to 3: [20 30 40]
Every second element: [10 30 50]
Reversed array: [60 50 40 30 20 10]


In [43]:
matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

print("Matrix:\n", matrix)
print("Element at row 1, col 2:", matrix[1, 2])
print("First row:", matrix[0, :])
print("First column:", matrix[:, 0])
print("Sub-matrix (rows 0-1, cols 1-2):\n", matrix[0:2, 1:3])

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, col 2: 6
First row: [1 2 3]
First column: [1 4 7]
Sub-matrix (rows 0-1, cols 1-2):
 [[2 3]
 [5 6]]
